name: X8bit
favicon: null
layout_spectrum: 0.95495
typography_spectrum: 0.74294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7bc3d3'
    - '#a7d6e1'
    - '#407b9a'
    - '#6da4c0'
  brandStrength: 1
  lightness: 0.5446176077239215
  saturation: 0.7975088332314044
  rhythmicContrast: 0.8804997256956995
purpose: []
